module.exports = {
    API_KEY: "",
    SECRET_KEY: "",
    SYMBOL: "AMPL-PERP",
    POSITION_SIZE: 10,
    NUM_BUY_GRID_LINES: 100,
    NUM_SELL_GRID_LINES: 100,
    GRID_SIZE: 0.01,
    CHECK_ORDERS_FREQUENCY: 1,
    CLOSED_ORDER_STATUS: 'closed',
    LOWER_PRICE: 0.5,
    UPPER_PRICE: 2,
    MIDDLE_PRICE: 1.1,
    GRID_NUM: 100,
    HOST: '',
    PORT: 3306,
    USER: "",
    PASSWORD: "",
    DATABASE: ""
};